
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 482878
	#The name of the modpack
	modpackName = "Better Minecraft [FORGE] 1.18.1"
	#The version of the modpack
	modpackVersion = "v12.5"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

